import Navbar from "@/components/Navbar";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"], // required
  weight: ["400", "500", "600", "700"], // choose font weights you need
  display: "swap", // prevents layout shift
});

export const metadata = {
  title: "BayHarbor Exports",
  description: "Generated by create next app",
 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased `}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
