import Navbar from "@/components/Navbar";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Suspense } from "react";
import Loading from "./loading";
import Footer from "@/components/Footer";
import FloatingContactButton from "@/components/FloatingContactButton";

const montserrat = Montserrat({
  subsets: ["latin"], // required
  weight: ["400", "500", "600", "700"], // choose font weights you need
  display: "swap", // prevents layout shift
});

export const metadata = {
  title: "BayHarbor Exports",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased `}>
        <Navbar />
        <Suspense fallback={<Loading />}>
          <main className="">{children}</main>
        </Suspense>
        <Footer />
        <FloatingContactButton />
      </body>
    </html>
  );
}
